In [1]:
"""
Data Ingestion and Profiling
Objective: To diagnose the raw dataset 
Required Python Packages
- pandas
- openpyxl
- pathlib(built into Python)

Tasks performed:
- Load all datasets
- Verify successful ingestion
- Inspect schema
- Assess data quality
- Document observations

** No modification to raw data.
"""

'\nData Ingestion and Profiling\nObjective: To diagnose the raw dataset \nRequired Python Packages\n- pandas\n- openpyxl\n- pathlib(built into Python)\n\nTasks performed:\n- Load all datasets\n- Verify successful ingestion\n- Inspect schema\n- Assess data quality\n- Document observations\n\n** No modification to raw data.\n'

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
data_path = Path("../data/raw")

World_Bank_File = data_path / "WorldBank.xlsx"
HDI_File = data_path / "HDI.csv"
Dictionary_File = data_path / "world_indicators_data_dictionary.csv"

In [4]:
print(World_Bank_File.exists())
print(HDI_File.exists())
print(Dictionary_File.exists())

True
True
True

In [5]:
world_bank = pd.read_excel(World_Bank_File)
hdi = pd.read_csv(HDI_File)
dictionary = pd.read_csv(Dictionary_File, encoding="latin1")

In [6]:
print("World Bank:", world_bank.shape)

print("HDI:", hdi.shape)

print("Data Dictionary:", dictionary.shape)

World Bank: (12449, 15)
HDI: (206, 1008)
Data Dictionary: (58, 3)

In [7]:
# Initial Dataset Inspection 
# understanding overall structure of each dataset

In [8]:
world_bank.head()

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
0,Afghanistan,AFG,South Asia,Low income,2018,NaN,NaN,NaN,1.936300e+10,520.897,NaN,47.9,NaN,56.9378,1.542
1,Afghanistan,AFG,South Asia,Low income,2017,33.211,6.575,NaN,2.019180e+10,556.302,13.50,49.5,64.130,55.5960,1.559
2,Afghanistan,AFG,South Asia,Low income,2016,33.981,6.742,NaN,1.936260e+10,547.228,11.20,51.2,63.763,54.1971,1.634
3,Afghanistan,AFG,South Asia,Low income,2015,34.809,6.929,NaN,1.990710e+10,578.466,8.26,53.1,63.377,52.7121,1.679
4,Afghanistan,AFG,South Asia,Low income,2014,35.706,7.141,NaN,2.048490e+10,613.856,7.00,55.1,62.966,51.1148,1.735

In [9]:
world_bank.tail()

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
12444,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1964,47.770,13.083,NaN,1.217138e+09,281.558,NaN,83.2,54.849,11.1745,NaN
12445,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1963,47.876,13.419,NaN,1.159512e+09,277.480,NaN,85.7,54.403,10.8019,NaN
12446,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1962,47.950,13.762,NaN,1.117602e+09,276.689,NaN,88.1,53.946,10.4413,NaN
12447,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1961,47.988,14.104,NaN,1.096647e+09,280.829,NaN,90.5,53.483,10.0944,NaN
12448,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1960,47.996,14.441,NaN,1.052990e+09,278.814,NaN,92.8,53.019,NaN,NaN

In [10]:
hdi.head()

,iso3,country,hdicode,region,hdi_rank_2021,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,...,mf_2012,mf_2013,mf_2014,mf_2015,mf_2016,mf_2017,mf_2018,mf_2019,mf_2020,mf_2021
0,AFG,Afghanistan,Low,SA,180.0,0.273,0.279,0.287,0.297,0.292,...,1.86,1.88,1.66,1.62,1.66,1.41,1.32,1.38,1.38,1.38
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,4.09,4.53,3.97,3.59,2.79,2.64,2.28,2.18,2.18,2.18
2,ALB,Albania,High,ECA,67.0,0.647,0.629,0.614,0.617,0.624,...,12.44,11.49,13.14,12.61,14.39,14.46,12.85,12.96,12.96,12.96
3,AND,Andorra,Very High,NaN,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Very High,AS,26.0,0.728,0.739,0.742,0.748,0.755,...,49.56,49.68,55.49,59.76,64.95,75.61,65.97,68.95,68.95,68.95

In [11]:
hdi.tail()

,iso3,country,hdicode,region,hdi_rank_2021,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,...,mf_2012,mf_2013,mf_2014,mf_2015,mf_2016,mf_2017,mf_2018,mf_2019,mf_2020,mf_2021
201,ZZG.ECA,Europe and Central Asia,NaN,NaN,NaN,0.664,0.661,0.654,0.652,0.647,...,13.107171,14.172082,14.189127,14.523162,13.791770,13.618078,13.914030,14.087293,14.091826,14.096719
202,ZZH.LAC,Latin America and the Caribbean,NaN,NaN,NaN,0.633,0.638,0.643,0.648,0.654,...,14.114108,14.493145,14.080904,14.146026,13.325144,13.604555,13.151315,13.296195,13.290914,13.284745
203,ZZI.SA,South Asia,NaN,NaN,NaN,0.442,0.447,0.453,0.457,0.462,...,4.699407,4.584935,4.486500,4.610546,4.624886,4.740263,5.000024,5.110230,5.106447,5.102134
204,ZZJ.SSA,Sub-Saharan Africa,NaN,NaN,NaN,0.407,0.410,0.410,0.411,0.413,...,3.437760,3.530479,3.491150,3.494860,3.415511,3.256156,3.145930,3.151076,3.146092,3.140740
205,ZZK.WORLD,World,NaN,NaN,NaN,0.601,0.604,0.607,0.610,0.614,...,12.186601,12.474065,12.520563,12.372667,12.277707,12.277878,12.220286,12.375236,12.325166,12.271920

In [12]:
dictionary.head()

       Table         Field                                     Description
0  WorldBank  Country Name                         The name of the country
1  WorldBank  Country Code  The three letter code representing the country
2  WorldBank        Region            The World Bank region of the country
3  WorldBank   IncomeGroup      The World Bank Income Group of the country
4  WorldBank          Year  The Year in which the statistics were recorded

In [13]:
dictionary.tail()

,Table,Field,Description
53,hdi,rankdiff_hdi_phdi_2021,Difference in HDI rank from 2020
54,hdi,phdi_xxxx,Planetary pressuresÐadjusted Human Development...
55,hdi,diff_hdi_phdi_xxxx,Difference from HDI value (%) in year xxxx
56,hdi,co2_prod_xxxx,Carbon dioxide emissions per capita (productio...
57,hdi,mf_xxxx,Material footprint per capita (tonnes) in year...

In [14]:
# Schema Inspection
# looking for column names, data types, non-null values, and memory usage for each dataset.

In [15]:
world_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 12449 entries, 0 to 12448
Data columns (total 15 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Country Name                                                  12449 non-null  str
 1   Country Code                                                  12449 non-null  str
 2   Region                                                        12449 non-null  str
 3   IncomeGroup                                                   12449 non-null  str
 4   Year                                                          12449 non-null  int64
 5   Birth rate, crude (per 1,000 people)                          11440 non-null  float64
 6   Death rate, crude (per 1,000 people)                          11416 non-null  float64
 7   Electric power consumption (kWh per capita)                   5848 non-null   float64
 8   GDP (USD)                                                     9578 non-null   float64
 9   GDP per capita (USD)                                          9575 non-null   float64
 10  Individuals using the Internet (% of population)              5064 non-null   float64
 11  Infant mortality rate (per 1,000 live births)                 9984 non-null   float64
 12  Life expectancy at birth (years)                              11176 non-null  float64
 13  Population density (people per sq. km of land area)           11845 non-null  float64
 14  Unemployment (% of total labor force) (modeled ILO estimate)  5208 non-null   float64
dtypes: float64(10), int64(1), str(4)
memory usage: 2.0 MB

In [16]:
hdi.info()

<class 'pandas.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Columns: 1008 entries, iso3 to mf_2021
dtypes: float64(1004), str(4)
memory usage: 1.6 MB

In [17]:
dictionary.info()

<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Table        58 non-null     str
 1   Field        58 non-null     str
 2   Description  58 non-null     str
dtypes: str(3)
memory usage: 5.3 KB

In [18]:
world_bank.dtypes

Country Name                                                        str
Country Code                                                        str
Region                                                              str
IncomeGroup                                                         str
Year                                                              int64
Birth rate, crude (per 1,000 people)                            float64
Death rate, crude (per 1,000 people)                            float64
Electric power consumption (kWh per capita)                     float64
GDP (USD)                                                       float64
GDP per capita (USD)                                            float64
Individuals using the Internet (% of population)                float64
Infant mortality rate (per 1,000 live births)                   float64
Life expectancy at birth (years)                                float64
Population density (people per sq. km of land area)             float64
Unemployment (% of total labor force) (modeled ILO estimate)    float64
dtype: object

In [19]:
hdi.dtypes

iso3                 str
country              str
hdicode              str
region               str
hdi_rank_2021    float64
                  ...
mf_2017          float64
mf_2018          float64
mf_2019          float64
mf_2020          float64
mf_2021          float64
Length: 1008, dtype: object

In [20]:
dictionary.dtypes

Table          str
Field          str
Description    str
dtype: object

In [21]:
hdi["country"].isna().sum()

np.int64(0)

In [22]:
world_bank.describe()

,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
count,12449.00000,11440.000000,11416.000000,5848.000000,9.578000e+03,9575.000000,5064.000000,9984.000000,11176.000000,11845.000000,5208.000000
mean,1989.00000,28.643276,10.588539,3175.294686,1.700740e+11,8231.812259,23.334471,51.704437,64.044692,318.861370,8.295079
std,17.03007,13.131893,5.489382,4467.139298,8.979866e+11,16173.539954,28.319388,46.131039,11.491087,1593.406041,6.290703
min,1960.00000,6.900000,1.127000,0.000000,8.824450e+06,34.790600,0.000000,1.400000,18.907000,0.098625,0.140000
25%,1974.00000,16.600000,6.863750,390.385750,1.393010e+09,513.145500,0.594949,14.475000,55.917750,19.783400,3.687000
50%,1989.00000,27.545500,9.200000,1541.895000,7.275305e+09,1852.810000,8.406225,37.000000,67.276000,64.007500,6.775000
75%,2004.00000,40.881250,12.687000,4313.767500,4.857782e+10,7774.565000,41.295950,78.200000,72.692250,144.823000,11.212250
max,2018.00000,58.227000,54.444000,54799.200000,2.050000e+13,189171.000000,100.000000,279.400000,85.417100,21389.100000,37.940000

In [23]:
hdi.describe()

,hdi_rank_2021,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,hdi_1995,hdi_1996,hdi_1997,hdi_1998,...,mf_2012,mf_2013,mf_2014,mf_2015,mf_2016,mf_2017,mf_2018,mf_2019,mf_2020,mf_2021
count,191.000000,152.000000,152.000000,152.000000,152.000000,152.000000,163.000000,163.000000,163.000000,163.000000,...,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000
mean,95.811518,0.595112,0.597862,0.600493,0.604474,0.609329,0.613908,0.619663,0.624975,0.630417,...,15.249784,15.385926,15.347629,15.352632,15.342119,15.491780,14.597416,14.776332,14.775408,14.774396
std,55.307333,0.161918,0.161921,0.162193,0.163122,0.163818,0.162789,0.163461,0.164299,0.165177,...,14.134572,14.555342,14.363092,14.680340,15.015809,15.333709,13.581871,14.266308,14.266504,14.266706
min,1.000000,0.216000,0.218000,0.222000,0.227000,0.232000,0.238000,0.243000,0.248000,0.256000,...,0.430000,0.420000,0.450000,0.560000,0.600000,0.610000,0.500000,0.470000,0.470000,0.470000
25%,48.500000,0.477750,0.477000,0.475250,0.474250,0.476500,0.480500,0.488500,0.490000,0.492000,...,4.597500,4.525000,4.452375,4.457500,4.517500,4.575000,4.612500,4.732500,4.732500,4.732500
50%,96.000000,0.621500,0.623500,0.622000,0.624000,0.623500,0.642000,0.650000,0.651000,0.657000,...,10.907725,11.272314,10.745000,10.260000,10.590000,10.895000,11.215000,11.030000,11.030000,11.030000
75%,143.500000,0.725500,0.727000,0.723750,0.724250,0.733750,0.737000,0.743000,0.752500,0.759000,...,20.345000,20.397500,20.227500,20.187500,19.350000,19.757500,18.432500,17.932500,17.932500,17.932500
max,191.000000,0.872000,0.873000,0.878000,0.880000,0.884000,0.885000,0.887000,0.890000,0.895000,...,74.560000,82.970000,81.100000,86.780000,83.510000,88.700000,71.160000,85.700000,85.700000,85.700000

In [24]:
world_bank.describe(include="str")

       Country Name Country Code                 Region          IncomeGroup
count         12449        12449                  12449                12449
unique          211          211                      7                    5
top     Afghanistan          AFG  Europe & Central Asia  Upper middle income
freq             59           59                   3304                 3127

In [25]:
hdi.describe(include="str")

       iso3      country    hdicode region
count   206          206        191    151
unique  206          206          4      6
top     AFG  Afghanistan  Very High    SSA
freq      1            1         66     46

In [26]:
# Missing Value Analysis
# Finding which columns have missing values, how many, is missingness systematic or random, variable at risk.

In [27]:
world_bank.isnull().sum

<bound method DataFrame.sum of        Country Name  Country Code  Region  IncomeGroup   Year  \
0             False         False   False        False  False
1             False         False   False        False  False
2             False         False   False        False  False
3             False         False   False        False  False
4             False         False   False        False  False
...             ...           ...     ...          ...    ...
12444         False         False   False        False  False
12445         False         False   False        False  False
12446         False         False   False        False  False
12447         False         False   False        False  False
12448         False         False   False        False  False

       Birth rate, crude (per 1,000 people)  \
0                                      True
1                                     False
2                                     False
3                                     False
4                                     False
...                                     ...
12444                                 False
12445                                 False
12446                                 False
12447                                 False
12448                                 False

       Death rate, crude (per 1,000 people)  \
0                                      True
1                                     False
2                                     False
3                                     False
4                                     False
...                                     ...
12444                                 False
12445                                 False
12446                                 False
12447                                 False
12448                                 False

       Electric power consumption (kWh per capita)  GDP (USD)  \
0                                             True      False
1                                             True      False
2                                             True      False
3                                             True      False
4                                             True      False
...                                            ...        ...
12444                                         True      False
12445                                         True      False
12446                                         True      False
12447                                         True      False
12448                                         True      False

       GDP per capita (USD)  Individuals using the Internet (% of population)  \
0                     False                                              True
1                     False                                             False
2                     False                                             False
3                     False                                             False
4                     False                                             False
...                     ...                                               ...
12444                 False                                              True
12445                 False                                              True
12446                 False                                              True
12447                 False                                              True
12448                 False                                              True

       Infant mortality rate (per 1,000 live births)  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False
...                                              ...
12444                                          False
12445                                          False
12446                                          False
12447                                          False
12448                                          False

       Life expectancy at birth (years)  \
0                                  True
1                                 False
2                                 False
3                                 False
4                                 False
...                                 ...
12444                             False
12445                             False
12446                             False
12447                             False
12448                             False

       Population density (people per sq. km of land area)  \
0                                                  False
1                                                  False
2                                                  False
3                                                  False
4                                                  False
...                                                  ...
12444                                              False
12445                                              False
12446                                              False
12447                                              False
12448                                               True

       Unemployment (% of total labor force) (modeled ILO estimate)
0                                                  False
1                                                  False
2                                                  False
3                                                  False
4                                                  False
...                                                  ...
12444                                               True
12445                                               True
12446                                               True
12447                                               True
12448                                               True

[12449 rows x 15 columns]>

In [28]:
hdi.isnull().sum()

iso3              0
country           0
hdicode          15
region           55
hdi_rank_2021    15
                 ..
mf_2017          38
mf_2018          38
mf_2019          38
mf_2020          38
mf_2021          38
Length: 1008, dtype: int64

In [29]:
def missing_value_summary(df):
    summary = df.isnull().sum().to_frame(name = "Missing Values")
    summary["Missing %"] = (summary["Missing Values"] / len(df) * 100).round(2)
    return summary.sort_values("Missing %", ascending = False)

In [30]:
missing_value_summary(world_bank)

                                                    Missing Values  Missing %
Individuals using the Internet (% of population)              7385      59.32
Unemployment (% of total labor force) (modeled ...            7241      58.17
Electric power consumption (kWh per capita)                   6601      53.02
GDP per capita (USD)                                          2874      23.09
GDP (USD)                                                     2871      23.06
Infant mortality rate (per 1,000 live births)                 2465      19.80
Life expectancy at birth (years)                              1273      10.23
Death rate, crude (per 1,000 people)                          1033       8.30
Birth rate, crude (per 1,000 people)                          1009       8.11
Population density (people per sq. km of land a...             604       4.85
IncomeGroup                                                      0       0.00
Country Name                                                     0       0.00
Year                                                             0       0.00
Country Code                                                     0       0.00
Region                                                           0       0.00

In [31]:
missing_value_summary(hdi).head(20)

                    Missing Values  Missing %
gdi_1992                        87      42.23
hdi_f_1990                      87      42.23
hdi_f_1991                      87      42.23
hdi_f_1992                      87      42.23
hdi_m_1990                      87      42.23
hdi_m_1992                      87      42.23
gdi_1991                        87      42.23
gdi_1990                        87      42.23
hdi_m_1991                      87      42.23
hdi_f_1993                      86      41.75
gdi_1993                        86      41.75
hdi_m_1994                      86      41.75
hdi_f_1994                      86      41.75
hdi_m_1993                      86      41.75
gdi_1994                        86      41.75
loss_2010                       82      39.81
ihdi_2010                       82      39.81
coef_ineq_2010                  82      39.81
diff_hdi_phdi_1990              81      39.32
phdi_1990                       81      39.32

In [32]:
missing_value_summary(dictionary)

             Missing Values  Missing %
Table                     0        0.0
Field                     0        0.0
Description               0        0.0

In [33]:
# Duplicate Analysis
# checking for duplicate values in the datasets.

In [34]:
world_bank.duplicated().sum()

np.int64(0)

In [35]:
hdi.duplicated().sum()

np.int64(0)

In [36]:
dictionary.duplicated().sum()

np.int64(0)

In [39]:
world_bank.duplicated(subset = ["Country Code","Year"]).sum()

np.int64(0)

In [40]:
hdi["iso3"].duplicated().sum()

np.int64(0)

In [41]:
dictionary.duplicated(subset = ["Field"]).sum()

np.int64(0)

In [42]:
world_bank["Country Name"].nunique()

211

In [43]:
world_bank["Country Code"].nunique()

211

In [45]:
world_bank["Year"].nunique()

59

In [46]:
world_bank["Region"].nunique()

7

In [47]:
world_bank["IncomeGroup"].nunique()

5

In [48]:
hdi["country"].nunique()

206

In [49]:
hdi["iso3"].nunique()

206

In [50]:
hdi["region"].nunique()

6

In [55]:
world_bank["Year"].min(), world_bank["Year"].max()

(np.int64(1960), np.int64(2018))

In [56]:
world_bank["GDP (USD)"].min(), world_bank["Population density (people per sq. km of land area)"].min()

(np.float64(8824450.0), np.float64(0.0986245))

In [59]:
world_bank["Country Code"].nunique() * world_bank["Year"].nunique()

12449

In [60]:
len(world_bank)

12449